apply plugin: 'com.android.library'

android {
    namespace "com.mixpush.oppo"

    compileSdkVersion 34

    defaultConfig {
        minSdkVersion 17

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(path: ':mixpush-core')
    implementation 'com.heytap.msp:push:3.0.0'
}
apply from: '../../maven_public.gradle'